# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Taper
email: bcb4y@virginia.edu
description: > # this means to ignore newlines until "baseurl:"
  UVA Library's source for information about copyright and publication issues
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thetaper.library.virginia.edu" # the base hostname & protocol for your site

disqus:
    shortname: thetaper

# Build settings
markdown: kramdown
theme: minima

github:
  repo: thetaper/dougchestnut.github.io
  branch: master

prose:
  siteurl: 'http://thetaper.library.virginia.edu/'
  #relativeLinks: 'http://thetaper.library.virginia.edu/links.jsonp'
  ignore:
    - .gitignore
    - "CNAME"
    - Gemfile
    - Gemfile.lock
    - README.md
    - index.md
    - _config.yml
    - /_posts/testpost
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: false
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          help: "Enable Disqus comments"
          value: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt"
          help: "Fill this in to provide an excerpt"
      - name: "excerpt_separator"
        field:
          element: "text"
          label: "Excerpt Separator"
          help: "If this is filled in, the entire post will be displayed up to the seperator placeholder."
          placeholder: "Replace with something like: <!--more-->"
